ALL: ej1 ej2 ej3 ej4
:PHONY= clean

ej1: ejercicio1.c
	gcc ejercicio1.c -o e1 -w -lpthread

ej2: ejercicio2.c
	gcc ejercicio2.c -o e2 -w -lpthread 

ej3: ejercicio3.c
	gcc ejercicio3.c -o e3 -w -lpthread

ej4: ejercicio4.c
	gcc ejercicio4.c -o e4 -w -lpthread

clean:
	\rm e1 e2 e3 e4
